import { expect, test } from '@playwright/test'

test('creates and rotates a Bearer credential through the UI with Vault TLS storage', async ({ page }, testInfo) => {
  await page.goto('/login')
  await page.getByLabel('用户名').fill('admin')
  await page.getByLabel('密码').fill('agentx-e2e-admin-password')
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await expect(page).toHaveURL(/\/$/)
  await page.getByRole('link', { name: '凭证', exact: true }).click()
  await page.getByRole('button', { name: '新建凭证', exact: true }).click()
  const form = page.getByRole('dialog', { name: '新建凭证', exact: true })
  const name = `Vault TLS credential ${Date.now()}`
  await form.getByLabel('名称', { exact: true }).fill(name)
  await form.getByRole('combobox', { name: '凭证类型' }).click()
  await page.getByRole('option', { name: 'Bearer Token', exact: true }).click()
  await form.getByLabel('密钥内容').fill('agentx-e2e-vault-placeholder-v1')
  await form.getByRole('combobox', { name: '所属部门' }).click()
  await page.getByRole('option', { name: 'Agentx P3-04 E2E', exact: true }).click()
  const created = page.waitForResponse((response) => response.request().method() === 'POST' && response.url().endsWith('/api/v1/credentials'))
  await form.getByRole('button', { name: '保存', exact: true }).click()
  const response = await created
  expect(response.status()).toBe(201)
  const credential = await response.json()
  expect(credential.currentSecretVersion).toBe(1)
  expect(JSON.stringify(credential)).not.toContain('agentx-e2e-vault-placeholder-v1')
  await expect(form).toBeHidden()
  const row = page.getByRole('row').filter({ hasText: name })
  await row.getByRole('link', { name: '详情', exact: true }).click()
  await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
  await page.getByRole('button', { name: '轮换密钥', exact: true }).click()
  const rotate = page.getByRole('dialog', { name: '轮换密钥', exact: true })
  await rotate.getByLabel('密钥内容').fill('agentx-e2e-vault-placeholder-v2')
  const rotated = page.waitForResponse((item) => item.request().method() === 'POST' && item.url().endsWith(`/api/v1/credentials/${credential.id}/rotate`))
  await rotate.getByRole('button', { name: '轮换密钥', exact: true }).click()
  const rotation = await rotated
  expect(rotation.status()).toBe(200)
  const result = await rotation.json()
  expect(result.currentSecretVersion).toBe(2)
  expect(JSON.stringify(result)).not.toContain('agentx-e2e-vault-placeholder-v2')
  await expect(rotate).toBeHidden()
  await expect(page.getByText('v2', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('vault-credential-rotated.png'), fullPage: true })
})
