static_resources:
  listeners:
    - name: http
      address:
        socket_address: {address: 0.0.0.0, port_value: 8080}
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: ingress_http
                cluster: ingress_http
                idle_timeout: 3600s
    - name: https
      address:
        socket_address: {address: 0.0.0.0, port_value: 8443}
      filter_chains:
        - filters:
            - name: envoy.filters.network.tcp_proxy
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                stat_prefix: ingress_https
                cluster: ingress_https
                idle_timeout: 3600s
  clusters:
    - name: ingress_http
      connect_timeout: 5s
      type: STATIC
      load_assignment:
        cluster_name: ingress_http
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: {address: 172.18.255.242, port_value: 80}
    - name: ingress_https
      connect_timeout: 5s
      type: STATIC
      load_assignment:
        cluster_name: ingress_https
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address: {address: 172.18.255.242, port_value: 443}
