use std::collections::BTreeMap;

use anyhow::Result;
use rcgen::{
    BasicConstraints, CertificateParams, DnType, ExtendedKeyUsagePurpose, IsCa, KeyPair,
    KeyUsagePurpose,
};

/// A local CA and its server identities. Production identities are supplied
/// by the platform, never generated by the installer.
pub struct LocalTlsMaterial {
    pub ca_certificate_pem: String,
    pub identities: BTreeMap<String, (String, String)>,
}

pub fn local_tls_material(subjects: &BTreeMap<String, Vec<String>>) -> Result<LocalTlsMaterial> {
    let mut params = CertificateParams::new(Vec::<String>::new())?;
    params
        .distinguished_name
        .push(DnType::CommonName, "Agentx local TLS CA");
    params.is_ca = IsCa::Ca(BasicConstraints::Unconstrained);
    params.key_usages = vec![KeyUsagePurpose::KeyCertSign, KeyUsagePurpose::CrlSign];
    let ca_key = KeyPair::generate()?;
    let ca = params.self_signed(&ca_key)?;
    let mut identities = BTreeMap::new();
    for (name, sans) in subjects {
        let mut params = CertificateParams::new(sans.clone())?;
        params.distinguished_name.push(DnType::CommonName, name);
        params.extended_key_usages = vec![ExtendedKeyUsagePurpose::ServerAuth];
        params.key_usages = vec![KeyUsagePurpose::DigitalSignature];
        let key = KeyPair::generate()?;
        let certificate = params.signed_by(&key, &ca, &ca_key)?;
        identities.insert(name.clone(), (key.serialize_pem(), certificate.pem()));
    }
    Ok(LocalTlsMaterial {
        ca_certificate_pem: ca.pem(),
        identities,
    })
}
